name: Continuous Delivery on prod functions

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/domains/functions**"
      - ".github/workflows/functions**.yml"

jobs:
  deploy:
    uses: pagopa/dx/.github/workflows/release-terraform-legacy-v1.yaml@main
    name: Deploy
    secrets: inherit
    with:
      dir: "src/domains/functions"
      azure_environment: prod
      environment: prod
      use_private_agent: true
